import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white selection:bg-white/20">
        <nav className="border-b border-white/5 bg-black/50 backdrop-blur-xl sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-6">
            <div className="flex justify-between h-16 items-center">
              <div className="flex items-center gap-10">
                <Link href="/" className="text-white font-medium tracking-widest text-[10px] hover:opacity-70 transition-opacity">
                  SOVEREIGN OS
                </Link>
                <div className="hidden sm:flex items-center gap-8">
                  <Link href="/" className="text-[10px] uppercase tracking-[0.2em] text-white/40 hover:text-white transition-colors">
                    Workspace
                  </Link>
                  <Link href="/memory" className="text-[10px] uppercase tracking-[0.2em] text-white/40 hover:text-white transition-colors">
                    Memory
                  </Link>
                </div>
              </div>
              <div className="flex items-center">
                <Link href="/settings" className="text-[10px] uppercase tracking-[0.2em] text-white/40 hover:text-white transition-colors">
                  Settings
                </Link>
              </div>
            </div>
          </div>
        </nav>
        <main className="flex-1 flex flex-col">{children}</main>
      </body>
    </html>
  );
}
